services:
  - type: web
    name: yolo-streamlit-app
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 10000 --server.address 0.0.0.0"

