services:
  - type: web
    name: image-classification
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    pythonVersion: "3.10"
